TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB_INSTALLS += $(TOP)/LXISup/devFC.db
DB_INSTALLS += $(TOP)/LXISup/devFC.proto
DB_INSTALLS += $(TOP)/LXISup/devScope.db
DB_INSTALLS += $(TOP)/LXISup/devScope.proto

#=======================================
include $(TOP)/configure/RULES
