TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB_INSTALLS += devFC.db
DB_INSTALLS += $(TOP)/FCSup/devFC.proto

#=======================================
include $(TOP)/configure/RULES
